// clang-format off
#pragma once

#define APP_CONTRAST_RECTANGLE_VERSION_CODE( major, minor, patch ) \
    ( ( ( major ) << 16UL ) + ( ( minor ) << 8UL ) + ( ( patch ) << 0UL ))

#define APP_CONTRAST_RECTANGLE_VERSION_MAJOR 0ull
#define APP_CONTRAST_RECTANGLE_VERSION_MINOR 1ull
#define APP_CONTRAST_RECTANGLE_VERSION_PATCH 0ull

// Consider to insert real revision here on CI:
#define APP_CONTRAST_RECTANGLE_VCS_REVISION "n/a"

#define APP_CONTRAST_RECTANGLE_VERSION \
    APP_CONTRAST_RECTANGLE_VERSION_CODE( APP_CONTRAST_RECTANGLE_VERSION_MAJOR, APP_CONTRAST_RECTANGLE_VERSION_MINOR, APP_CONTRAST_RECTANGLE_VERSION_PATCH )

